# models/sources.yml (ou onde você preferir organizar suas sources)

version: 2

sources:
  - name: raw_data # Este nome deve corresponder ao primeiro argumento em {{ source() }}
    database: postgres # Opcional se já estiver no profiles.yml, mas boa prática
    schema: raw_data # <<<<<<< ESTE É O PONTO CRÍTICO: onde a tabela 'clientes' realmente está
    tables:
      - name: clientes 
      - name: enderecos
      - name: produtos
      - name: pedidos
      - name: pagamentos
